apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-operator
spec:
  selector:
    matchLabels:
      app: nginx-operator
  template:
    metadata:
      labels:
        app: nginx-operator
    spec:
      serviceAccountName: nginx-operator
      containers:
       - image: pearlsprathap/nginx-operator
         name: nginx-operator
